baseURL: https://bazclearance.co.uk/
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false

sitemap:
    changeFreq: daily
    filename: sitemap.xml
    priority: 0
